api/config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:show, :index]
  resources :users, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

api/app/models/event.rb
class Event < ApplicationRecord
  has_many :rsvps
  has_many :users, through: :rsvps

  validates :title, :starttime, presence: true
  validates :allday, inclusion: [true, false]
  validates :endtime, presence: true, if: :timed_event?
  validates :complete, inclusion: [true, false]

  before_create :check_validity, :check_completion
  
  scope :valid_dates, -> { where('starttime < endtime') }
  scope :after_startdate, -> (date) { where('starttime >= ?', date) }
  scope :before_enddate, -> (date) { where('endtime <= ?', date) }

  def self.seed_data row
    transaction do 
      event = create_from_csv row
      begin
        row[4].split(';').each do |subrow|
          Rsvp.seed_data subrow.split('#') << event
        end
      rescue
        SeedError.create(description: event.title)
      end
    end
  end

  def self.create_from_csv row
    event = new(
      title: row[0],
      description: row[3],
      allday: row[5],
      starttime: row[1] ||= nil,
      endtime: row[2] ||= nil,
    )
    event.save
    event
  end

  def check_validity
    self.endtime = nil if self.allday == true
  end

  def check_completion
    self.complete = true if self.endtime && Time.now > self.endtime
  end

  def timed_event?
    !self.allday
  end

  def self.fetch from, to
    return Event.valid_dates.after_startdate(from).before_enddate(to) if Chronic::Event.valid? from, to
    []
  end
end

api/app/models/rsvp.rb
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event

  before_create :check_overlaps
  
  def self.seed_data row
    Rsvp.create(response: row[1], user_id: User.find_by_username(row[0]).id, event_id: row[2].id)
  end

  private

  def check_overlaps
    self.response = 'no' if self.user.events.where('starttime < ? AND endtime > ? AND response = "yes"', self.event.starttime, self.event.starttime).present?
  end
end

api/app/models/seed_error.rb
class SeedError < ApplicationRecord
end

api/app/models/user.rb
class User < ApplicationRecord
  has_many :rsvps
  has_many :events, through: :rsvps

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  def self.seed_data row
    User.create(username: row[0], email: row[1], phone: row[2])
  end
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include ActionController::RequestForgeryProtection
  protect_from_forgery with: :exception
end

api/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: :show

  # GET /events
  # GET /events.json
  def index
    @events = Event.fetch params[:from], params[:to]
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :starttime, :endtime, :description, :allday)
  end
end

api/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :phone)
  end
end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/helpers/events_helper.rb
module EventsHelper
end

api/app/helpers/users_helper.rb
module UsersHelper
end

api/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :starttime %>
    <%= form.datetime_select :starttime, id: :event_starttime %>
  </div>

  <div class="field">
    <%= form.label :endtime %>
    <%= form.datetime_select :endtime, id: :event_endtime %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :event_description %>
  </div>

  <div class="field">
    <%= form.label :allday %>
    <%= form.check_box :allday, id: :event_allday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

api/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Description</th>
      <th>Allday</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td></td>
      <td id='start-date' class='range'><%= date_field_tag(:datetime_ida) %><button class='go'>Go</button></td>
      <td id='end-date' class='range'><%= date_field_tag(:datetime_ida) %><button class='go'>Go</button></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.starttime %></td>
        <td><%= event.endtime %></td>
        <td><%= event.description %></td>
        <td><%= event.allday %></td>
        <td><%= event.complete %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type='text/javascript'>
  $(document).ready(() => {
    var startdate, enddate
    $('td button.go').click((e) => {
      startdate = $('td#start-date input').val();
      enddate = $('td#end-date input').val();
      window.location.href=`http://localhost:3000/events?startdate=${startdate}&enddate=${enddate}`
    });
  })
</script>

api/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @event.starttime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @event.endtime %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Allday:</strong>
  <%= @event.allday %>
</p>

<%= link_to 'Back', events_path %>

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventsOnRails</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

api/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :user_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

api/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

api/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Back', users_path %>